//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEgitimKampi301.EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomer
    {
        public int customerid { get; set; }
        public string customername { get; set; }
        public string customersurname { get; set; }
        public Nullable<decimal> customerbalance { get; set; }
    }
}
