//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEgitimKampi301.EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllocation
    {
        public int locationid { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<byte> capacity { get; set; }
        public Nullable<decimal> price { get; set; }
        public string daynight { get; set; }
        public Nullable<int> guideid { get; set; }
    
        public virtual tblguide tblguide { get; set; }
    }
}
